In [ ]:
# %%

# À ex'écuter en premier
import numpy as np

In [ ]:
# %%

# À ex'écuter en premier
import numpy as np

In [ ]:
# %%

# À ex'écuter en premier
import numpy as np

# %% [markdown]

 # Niveau 1 : Création de tableaux simples

# %% [markdown]

 ## Exercices 1.1.	Créer un tableau de 5 zéros

 Compléter la fonction `create_zeros` pour qu'elle retourne un tableau de 5 éléments égaux à 0.

In [ ]:
# %%

def create_zeros():
    return np.zeros(5)  # 👈 Insérez le code ici


print(create_zeros())  # attendu: [0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0.]


# %% [markdown]

 ## Exercices 1.2.	Créer un tableau de 5 uns

 Compléter la fonction `create_ones` pour qu'elle retourne un tableau de 5 éléments égaux à 1.

In [ ]:
# %%

def create_ones():
    return np.ones(5)  # 👈 Insérez le code ici


print(create_ones())  # attendu: [1. 1. 1. 1. 1.]

[1. 1. 1. 1. 1.]


# %% [markdown]

 ## Exercices 1.3.	Créer un tableau contenant les entiers de 10 à 50

 Compléter la fonction `create_range` pour qu'elle retourne un tableau contenant les entiers de 10 à 50 inclus.

In [ ]:
# %%

def create_range():
    return np.arange(10,51)  # 👈 Insérez le code ici


print(create_range())  # attendu: [10 11 12 13 14 15 16 17 ...] (jusqu'à 50 inclus)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


# %% [markdown]

 ## Exercices 1.4.	Créer une matrice identité 3x3

 Compléter la fonction `create_identity` pour qu'elle retourne une matrice identité de taille 3x3.

In [ ]:
# %%

def create_identity():
    return np.array([[1,0,0],[0,1,0],[0,0,1]])  # 👈 Insérez le code ici


print(create_identity())  # attendu: [[1. 0. 0.]
#                                     [0. 1. 0.]
#                                     [0. 0. 1.]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# %%

def create_identity():
    return np.array([[1.,0,0],[0,1.,0],[0,0,1.]])  # 👈 Insérez le code ici


print(create_identity())  # attendu: [[1. 0. 0.]
#                                     [0. 1. 0.]
#                                     [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# %% [markdown]

 ## Exercices 1.5.	Créer un tableau 2D de forme (3,3) rempli de nombres aléatoires entre 0 et 1

 Compléter la fonction `create_random` pour qu'elle retourne un tableau 2D de forme (3,3) rempli de nombres aléatoires entre 0 et 1.

In [ ]:
# %%

def create_random():
    return np.random((3,3))  # 👈 Insérez le code ici


print(create_random())  # attendu: un tableau 3x3 de valeurs aléatoires entre 0 et 1

TypeError: 'module' object is not callable

In [ ]:
# %%

def create_random():
    return np.random.randn((3,3))  # 👈 Insérez le code ici


print(create_random())  # attendu: un tableau 3x3 de valeurs aléatoires entre 0 et 1

TypeError: 'tuple' object cannot be interpreted as an integer

In [ ]:
# %%

def create_random():
    return np.random.randn(shape=(3,3))  # 👈 Insérez le code ici


print(create_random())  # attendu: un tableau 3x3 de valeurs aléatoires entre 0 et 1

TypeError: randn() got an unexpected keyword argument 'shape'

In [ ]:
# %%

def create_random():
    return np.random.randn(3,3)  # 👈 Insérez le code ici


print(create_random())  # attendu: un tableau 3x3 de valeurs aléatoires entre 0 et 1

[[-0.79268498 -1.53902432 -0.75753228]
 [-0.24790708 -2.39609991 -0.36032834]
 [ 0.21216695 -0.91092152  0.14791942]]
